# Site settings
title_chinese: 百炼成仙
title: Tempered Immortal
author_chinese: 幻雨
author: Magic Rain
email: blcxtranslations@gmail.com
baseurl: "/blcx"
url: "https://blcxtranslations.github.io"
description: "A young man with no spiritual roots. A person who is thought of as trash by others. He constantly acquires various items thought of as waste by the cultivation world. No matter if it is garbage pills or useless materials, he will take them all!"

timezone: America/Toronto

# Build settings
markdown: kramdown

collections:
  translated:
    output: true
    permalink: /:path:output_ext
